services:
  db:
    container_name: postgres
    image: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    build:
      context: .
      dockerfile: ./build/postgres.Dockerfile
    volumes:
      - postgresdb-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - ouzi-network
  main:
    depends_on:
    - db
    container_name: mainService
    build:
      context: ./
      dockerfile: ./build/main.Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - .env
    volumes:
      - "ouzi_dir:/ouzi/audio"  # Именованный volume для хранения аудио
      - "./examples/hello.wav:/ouzi/examples/hello.wav"  # Bind mount для локального файла
    networks:
      - ouzi-network
  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"  # Указываем локальный путь /data
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # Console
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - minio_data:/data  # Том для хранения данных
    networks:
      - ouzi-network
  minioclient:
      depends_on:
        - minio
        - db
      container_name: minioClient
      build:
        context: ./
        dockerfile: ./build/minioClient.Dockerfile
      ports:
        - '8081:8081'
      env_file:
        - .env
      networks:
        - ouzi-network

volumes:
  ouzi_dir:  # Именованный volume
    driver: local
  minio_data:  # Именованный volume для MinIO
    driver: local
  postgresdb-data:
    driver: local

networks:
  ouzi-network:
    name: ouzi-network
    driver: bridge
