services:
  main:
    container_name: mainService
    build:
      context: ./
      dockerfile: ./build/main.Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - .env
    volumes:
      - "ouzi_dir:/ouzi/audio"
    networks:
      - ouzi-network


volumes:
  ouzi_dir:  # Определяем именованный volume
    driver: local

networks:
  ouzi-network:
    name: ouzi-network
    driver: bridge