services:
  main:
    container_name: mainService
    build:
      context: ./
      dockerfile: ./build/main.Dockerfile
    ports:
      - '8080:8080'
    env_file:
      - .env
    volumes:
      - "ouzi_dir:/ouzi/audio"  # Именованный volume для хранения аудио
      - "./examples/hello.wav:/ouzi/examples/hello.wav"  # Bind mount для локального файла
    networks:
      - ouzi-network

volumes:
  ouzi_dir:  # Именованный volume
    driver: local

networks:
  ouzi-network:
    name: ouzi-network
    driver: bridge